export const categoryFullInfo = [
  {
    _id: 1,
    title: "Long sleeve Jacket",
    isNew: true,
    oldPrice: "200",
    price: 150,
    discountedPrice: 135,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.",
    category: "women",
    type: "jacket",
    stock: 50,
    brand: "FashionTrend",
    size: ["S", "M", "L"],
    image: "https://images.pexels.com/photos/2584269/pexels-photo-2584269.jpeg",
    rating: 4,
  },
  {
    _id: 2,
    title: "Jacket with wollen hat",
    isNew: true,
    oldPrice: "70",
    price: 65,
    discountedPrice: 58.5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.",
    category: "women",
    type: "jacket",
    stock: 30,
    brand: "CozyWear",
    size: ["M", "L", "XL"],
    image: "https://images.pexels.com/photos/2681751/pexels-photo-2681751.jpeg",
    rating: 3,
  },
 
  {
    _id: 8,
    title: "Gouwn with Red velvet",
    isNew: false,
    oldPrice: "500",
    price: 350,
    discountedPrice: 315,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.",
    category: "women",
    type: "gown",
    stock: 15,
    brand: "LuxuryDress",
    size: ["S", "M"],
    image: "https://images.pexels.com/photos/2233703/pexels-photo-2233703.jpeg",
    rating: 3,
  },
  {
    _id: 9,
    title: "Pink beauty",
    isNew: false,
    oldPrice: "150",
    price: 100,
    discountedPrice: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.",
    category: "women",
    type: "dress",
    stock: 25,
    brand: "ChicStyle",
    size: ["S", "M", "L"],
    image: "https://images.pexels.com/photos/2065195/pexels-photo-2065195.jpeg",
    rating: 3,
  },
  {
    _id: 10,
    title: "Jean's stylish Jacket",
    isNew: false,
    oldPrice: "250",
    price: 245,
    discountedPrice: 220.5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.",
    category: "men",
    type: "jacket",
    stock: 35,
    brand: "DenimCo",
    size: ["M", "L", "XL"],
    image: "https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg",
    rating: 5,
  },
  
  {
    _id: 18,
    title: "Khakhi jeans",
    isNew: false,
    oldPrice: "250",
    price: 190,
    discountedPrice: 171,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.",
    category: "women",
    type: "jeans",
    stock: 65,
    brand: "DenimCo",
    size: ["28", "30", "32", "34"],
    image: "https://images.pexels.com/photos/3054973/pexels-photo-3054973.jpeg",
    rating: 4,
  },

  {
    _id: 20,
    title: "Formal for Men",
    isNew: false,
    oldPrice: "500",
    price: 490,
    discountedPrice: 441,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.",
    category: "men",
    type: "suit",
    stock: 20,
    brand: "FormalFit",
    size: ["M", "L", "XL"],
    image: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg",
    rating: 5,
  },
];
